mysql:
  host: localhost
  port: 3306
  username: root
  password: root
  database: skillfull


redis:
  host: localhost
  port: 6379
  password: root
  database: 15


app:
  server-port: 8102
  context-path: /skill
  log-root-level: info
  upload-folder: ./upload
  log-package-level: debug
  swagger-enable: true # 是否打开swagger
  create-out-conf: false  # 启动是否创建外置配置文件
